# Generated by Django 3.1.7 on 2021-03-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='examination_after_a_period',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='employee',
            name='serial_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
